### PR TITLE
Fixed Take and Skip methods

### PR DESCRIPTION
**Pull request by un-tone**
I've checked - this approach works faster than approach with `Db.SlowSql` and literals.

### CODE REVIEW

**Comment by rogeralsing** [comment]
This will fail for `CompiledQuery` as compiled queries take the incoming user variables and pass them directly to fill the variables in the SQL.
The approach in this commit, would require this user variable array and append the offset/limit literals to this array.

e.g.
lets say I have a CompiledQuery like so:

`Func<int,IEnumerable<Person>> ByAge = CompiledQuery<int,IEnumerable<Person>>(int age, () => Objects<Person>().Where(p => p.Age == age).Skip(10)`

(Not syntax checked, written from the top of my mind so it could be errors)

When executing this, there will be a single variable (age), while the SQL expects age and 10.

I am not sure if there is a decent way to fix this as any special literal like this would have to be inserted at the correct place in the variable array, which is likely slower than just doing plain text sql literals.

**Comment by miyconst** [comment]
@rogeralsing, I would rather prohibit users compile queries with literals than use `Db.SlowSql` underneath.

Automatically appending values to the parameters list may not only be expensive, but also difficult to implement.

For example this query:

```cs
Objects<Person>().Where(x => x.Name == name).Take(10).FirstOrDefault(x => x.Surname == surname);
```

I know, it does not make much sense, and in Starcounter we don't (yet) support sub queries, but in this case the extra `Take` value should be inserted with correct index.

**Comment by rogeralsing** [comment]
I'm strongly against removing literals from compiled queries.

SlowSQL is 1.1-1.2 times slower than SQL from my tests (this might be wrong)

Translating Linq is ~5 times slower than raw SQL (using our provider)

So avoiding SlowSQL for performance purposes in favor for ad-hoc Linq makes little sense as the end result will be much much slower and cost more resources.

Compiled Queries moves Linq up to the same speed as SlowSql.

And avoiding literals in CompiledQueries will render compiled queries pretty much useless, you will only be able to match on _some_ parameters. features like Contains/StartsWith/EndsWith will stop working.

my 2 cents

**Comment by miyconst** [comment]
Okay. Let's just keep the literals in the compiled queries and use `Db.SlowSql`. If for whatever reason we decide that it's not good enough, we will be able to adjust it later.

**Comment by un-tone** [comment]
Thanks for the explanations. Closing this PR...

**Pull request closed without merging**
