### PR TITLE
Throw exception when null value is passed to a complied query

### PR DESCRIPTION
**Pull request by un-tone**
By @joozek78's proposal for https://github.com/Starcounter/Starcounter.Linq/issues/62.
Approve if you agree with the solution.

### CODE REVIEW

**Comment by un-tone** [comment]
@mtornwall Updated, please check.

**Comment by joozek78** [comment]
I understood that it's possible to compile a query with null, like this:

```c#
DbLinq.CompileQuery(() =>
    DbLinq.Objects<Foo>().Where(o => o.Name == null)
);
```

What isn't possible is passing `null` to a compiled query like this:
```c#
var query = DbLinq.CompileQuery((Foo compareAgainst) =>
    DbLinq.Objects<Foo>().Where(o => o == compareAgainst)
);
query(null);
```

**Comment by un-tone** [comment]
@joozek78 in case 1 we have the following translated SQL query:

```sql
SELECT F FROM "Foo" F WHERE F."Name" IS NULL
```

while in case 2 we have:

```sql
SELECT F FROM "Foo" F WHERE F."Name" = ?
```

**Comment by un-tone** [comment]
@mtornwall I think `DbLinq.IsNull` will only confuse developers. Why not write just ` == null` if you know that the passed value is `null`? This is how it works with all other LINQ Providers, it is common sense for many developers. And troubles come only when a "compiled query" is used, not a regular LINQ query.

Now I think what if for compiled query we'll prepare more than one translated SQL queries? For example, for

```cs
DbLinq.CompileQuery((Foo compareAgainst) =>
    DbLinq.Objects<Foo>().Where(o => o == compareAgainst && o.Name == name)
)
```

it will be:

```sql
SELECT F FROM "Foo" F WHERE F = ? AND F."Name" = ?
SELECT F FROM "Foo" F WHERE F = IS NULL AND F."Name" = ?
SELECT F FROM "Foo" F WHERE F = ? AND F."Name" IS NULL
SELECT F FROM "Foo" F WHERE F = IS NULL AND F."Name" IS NULL
```
And on executing it will check which parameters is null and select most appropriate SQL query. Looks reasonable.

**Comment by mtornwall** [comment]
> I think DbLinq.IsNull will only confuse developers. Why not write just == null if you know that the passed value is null?

Totally agree, I'm being stupid.

**Comment by miyconst** [comment]
>Now I think what if for compiled query we'll prepare more than one translated SQL queries? For example, for..

My two cents is that this would be perfect.

>So I thought about this some more. `IS NULL` is a perfectly legitimate condition. Could we support something like this as a replacement:

@mtornwall a custom `DbLinq.IsNull` function would only make sense if there would be a database SQL operator for that, like [`T-SQL ISNULL(expression, replacement)`](https://docs.microsoft.com/en-us/sql/t-sql/functions/isnull-transact-sql?view=sql-server-2017), which allows to make such constructions:

```sql
SELECT p
FROM Product
WHERE ISNULL(p.Price, 0) = ISNULL(@inputParameterName, 0) 
```

**Comment by un-tone** [comment]
Should we merge this PR while we didn't have the other implemented [solution](https://github.com/Starcounter/Starcounter.Linq/pull/66#issuecomment-439995817)? I still didn't have enough time to move forward much with it, so we could have now at least this solution.
@miyconst @mtornwall

**Comment by mtornwall** [comment]
> Should we merge this PR while we didn't have the other implemented solution?

I think yes.

**Pull request merged**
